### ISSUE TITLE
Await function does not gets execute.

### ISSUE THREAD

**Issue by sachinpatel248** [kashifmin/flutter_tensorflow_lite#1]
I have taken the sample example as shown README.md (which is same as mentioned at [https://pub.dartlang.org/packages/tensorflow_lite#-example-tab-](url) ) with appropriate instruction.

When I run the app keeps on loading; when debugged, the below await function gets stuck and does not responds with no output/error message.
`var classifier = await TFLiteImageClassifier.createInstance(
      assets: rootBundle,
      modelPath: "assets/assetsmobilenet_quant_v1_224.tflite",
      labelPath: "assets/labels.txt",
      inputSize: 224,
    );
`

**My pubspec.yaml-**
`name: ai_edge
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  tensorflow_lite: ^0.0.3
  image: ^1.1.32

dev_dependencies:
  flutter_test:
    sdk: flutter

assets:
     - assets/mobilenet_quant_v1_224.tflite
     - assets/cat_Image.jpg-
     - assets/labels.txt
	 
flutter:
  uses-material-design: true
`

Is there something which I missed.

**Comment by kashifmin** [comment]
Hi there,
Can you add this line in your app level `build.gradle` and let me know if it works?

```gradle
    // prevent model file from being compressed
    aaptOptions {
        noCompress "tflite"
        noCompress "lite"
    }
```

Check the example app build.gradle: https://github.com/kashifmin/flutter_tensorflow_lite/blob/master/android/build.gradle#L40

**Comment by sachinpatel248** [comment]
**Hi Kashif Minhaj,**

I have added this suggested changes in android/app/build.gradle and now its showing errors.



### Debug Console Errors

`Launching lib\main.dart on Moto G 5 Plus in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk (54.1MB).
I/FlutterActivityDelegate(14479): onResume setting current activity to this
I/FlutterActivityDelegate(14479): onResume setting current activity to this
D/TensorflowLitePlugin(14479): called : createInterpreterInstance
D/TensorflowLitePlugin(14479): 
### Asset key is flutter_assets/assets/mobilenet_quant_v1_224.tflite
E/FlutterNativeView(14479): Uncaught exception in binary message listener
E/FlutterNativeView(14479): 
### java.io.FileNotFoundException: flutter_assets/assets/mobilenet_quant_v1_224.tflite
E/FlutterNativeView(14479): 	at android.content.res.AssetManager.openAssetFd(Native Method)
E/FlutterNativeView(14479): 	at android.content.res.AssetManager.openFd(AssetManager.java:363)
E/FlutterNativeView(14479): 	at me.kashifminhaj.tensorflowlite.TensorflowLitePlugin.loadModelFile(TensorflowLitePlugin.kt:86)
E/FlutterNativeView(14479): 	at me.kashifminhaj.tensorflowlite.TensorflowLitePlugin.createInterpreterInstance(TensorflowLitePlugin.kt:60)
E/FlutterNativeView(14479): 	at me.kashifminhaj.tensorflowlite.TensorflowLitePlugin.onMethodCall(TensorflowLitePlugin.kt:45)
E/FlutterNativeView(14479): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/FlutterNativeView(14479): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:136)
E/FlutterNativeView(14479): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/FlutterNativeView(14479): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/FlutterNativeView(14479): 	at android.os.Looper.loop(Looper.java:136)
E/FlutterNativeView(14479): 	at android.app.ActivityThread.main(ActivityThread.java:6123)
E/FlutterNativeView(14479): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterNativeView(14479): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
E/FlutterNativeView(14479): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
E/flutter (14479): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (14479): MissingPluginException(No implementation found for method createInterpreterInstance on channel tensorflow_lite)
E/flutter (14479): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
E/flutter (14479): <asynchronous suspension>
E/flutter (14479): #1      Interpreter.createInstance (package:tensorflow_lite/tensorflow_lite.dart:34:20)
E/flutter (14479): <asynchronous suspension>
E/flutter (14479): #2      TFLiteImageClassifier.createInstance (file:///C:/Users/Sachin13390/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/tensorflow_lite-0.0.3/lib/src/tflite_image_classifier.dart:20:49)
E/flutter (14479): <asynchronous suspension>
E/flutter (14479): #3      _MyAppState.loadRecognitions (file:///D:/Product/AI_EDGE/ai_edge/lib/main.dart:26:50)
E/flutter (14479): <asynchronous suspension>
E/flutter (14479): #4      _MyAppState.initState (file:///D:/Product/AI_EDGE/ai_edge/lib/main.dart:22:5)
E/flutter (14479): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3743:58)
E/flutter (14479): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
E/flutter (14479): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
E/flutter (14479): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
E/flutter (14479): #9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
E/flutter (14479): #10     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
E/flutter (14479): #11     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
E/flutter (14479): #12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2214:19)
E/flutter (14479): #13     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
E/flutter (14479): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
E/flutter (14479): #15     runApp (package:flutter/src/widgets/binding.dart:704:7)
E/flutter (14479): #16     main (file:///D:/Product/AI_EDGE/ai_edge/lib/main.dart:9:16)
E/flutter (14479): #17     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
E/flutter (14479): #18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
`


### Now it seems that app is not able to find the tfLite mode l but I have placed assets folder containing model and other resources in app folder.

**Comment by kashifmin** [comment]
Can you send me the output of `flutter doctor`
I am not able to reproduce the error here. Maybe you could upload your code somewhere and I can try it out?
I have compiled a fresh example app and it works fine with latest Flutter version.
https://github.com/kashifmin/tensorflow_lite_test

**Comment by sachinpatel248** [comment]
I tried with your example app and it worked like a charm. As requested I have uploaded my app at [https://github.com/sachinpatel248/ai_edge](url). 

### Debug Console

**flutter** doctor -v
[√] Flutter (Channel beta, v0.3.2, on Microsoft Windows [Version 10.0.14393], locale en-US)
    • Flutter version 0.3.2 at D:\Product\flutter
    • Framework revision 44b7e7d3f4 (5 weeks ago), 2018-04-20 01:02:44 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Sachin13390\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-P, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[!] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.23.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.12.1

[√] Connected devices (1 available)
    • Moto G 5 Plus • ZY2243G9NH • android-arm • Android 7.0 (API 24)

! Doctor found issues in 1 category.

**Comment by kashifmin** [comment]
The asset not found error seems to be associated with your cat_Image.png file. Your image's extension is .jpg but you had specified .png
https://github.com/sachinpatel248/ai_edge/blob/master/lib/main.dart#L33
Also replace `img.decodePng()` with `img.decodeJpg()`

It worked fine after making these changes.

**Comment by sachinpatel248** [comment]
Hi Kashif Minhaj,

Thanks for helping me out. 
And apologies to trouble you for such a silly mistakes
