### ISSUE TITLE
your sample does it not work

### ISSUE THREAD

**Issue by rhelenagh** [kashifmin/flutter_tensorflow_lite#2]
Hello,
I have tried to run your example, but unfortunately it does not work.
You have tried it, it works for you ?.
Thanks for your time and information.

rhelena

**Comment by lgeo3** [comment]
It works fine for me (I am just a user).

**Comment by rhelenagh** [comment]
Hello Laurent-george

I have done the test with the emulator and with a real device.
in both cases I get the following error.
You have some idea, that you can help me.
Thank you very much.



D/TensorflowLitePlugin( 3929): called : createInterpreterInstance
D/TensorflowLitePlugin( 3929): Asset key is flutter_assets/assets/mobilenet_quant_v1_224.tflite
E/FlutterNativeView( 3929): Uncaught exception in binary message listener
E/FlutterNativeView( 3929): java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
E/FlutterNativeView( 3929): 	at android.content.res.AssetManager.openAssetFd(Native Method)
E/FlutterNativeView( 3929): 	at android.content.res.AssetManager.openFd(AssetManager.java:363)
E/FlutterNativeView( 3929): 	at me.kashifminhaj.tensorflowlite.TensorflowLitePlugin.loadModelFile(TensorflowLitePlugin.kt:86)
E/FlutterNativeView( 3929): 	at me.kashifminhaj.tensorflowlite.TensorflowLitePlugin.createInterpreterInstance(TensorflowLitePlugin.kt:60)
E/FlutterNativeView( 3929): 	at me.kashifminhaj.tensorflowlite.TensorflowLitePlugin.onMethodCall(TensorflowLitePlugin.kt:45)
E/FlutterNativeView( 3929): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/FlutterNativeView( 3929): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:152)
E/FlutterNativeView( 3929): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/FlutterNativeView( 3929): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/FlutterNativeView( 3929): 	at android.os.Looper.loop(Looper.java:136)
E/FlutterNativeView( 3929): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
E/FlutterNativeView( 3929): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterNativeView( 3929): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/FlutterNativeView( 3929): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
I/Choreographer( 3929): Skipped 53 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 3929): eglMakeCurrent: 0xa8c853c0: ver 3 0 (tinfo 0xa8c83290)
E/flutter ( 3929): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 3929): MissingPluginException(No implementation found for method createInterpreterInstance on channel tensorflow_lite)
E/flutter ( 3929): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
E/flutter ( 3929): <asynchronous suspension>
E/flutter ( 3929): #1      Interpreter.createInstance (package:tensorflow_lite/tensorflow_lite.dart:34:20)
E/flutter ( 3929): <asynchronous suspension>
E/flutter ( 3929): #2      TFLiteImageClassifier.createInstance (file:///D:/flutter/.pub-cache/hosted/pub.dartlang.org/tensorflow_lite-0.0.3/lib/src/tflite_image_classifier.dart:20:49)
E/flutter ( 3929): <asynchronous suspension>
E/flutter ( 3929): #3      _MyAppState.loadRecognitions (file:///D:/Repository/flutterApps/tensor/lib/main.dart:26:50)
E/flutter ( 3929): <asynchronous suspension>
E/flutter ( 3929): #4      _MyAppState.initState (file:///D:/Repository/flutterApps/tensor/lib/main.dart:22:5)
E/flutter ( 3929): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3751:58)
E/flutter ( 3929): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter ( 3929): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter ( 3929): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter ( 3929): #9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
E/flutter ( 3929): #10     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
E/flutter ( 3929): #11     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
E/flutter ( 3929): #12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
E/flutter ( 3929): #13     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
E/flutter ( 3929): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
E/flutter ( 3929): #15     runApp (package:flutter/src/widgets/binding.dart:704:7)
E/flutter ( 3929): #16     main (file:///D:/Repository/flutterApps/tensor/lib/main.dart:9:16)
E/flutter ( 3929): #17     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
E/flutter ( 3929): #18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
D/        ( 3929): HostConnection::get() New Host Connection established 0xa8c88680, tid 3971
D/EGL_emulation( 3929): eglMakeCurrent: 0xa44f4a00: ver 3 0 (tinfo 0xa8c83220)

**Comment by kashifmin** [comment]
Hi @rhelenagh 

Please refer to the solution posted by me in this issue: https://github.com/kashifmin/flutter_tensorflow_lite/issues/1

If you're still facing the same problem, you could share the code snippets so that I can help you debug it.

**Comment by rhelenagh** [comment]
Hi @kashifmin 

After your recommendations, your example works correctly.
I suggest you include in your package description (https://pub.dartlang.org/packages/tensorflow_lite#-readme-tab-) your comments as a note.

  aaptOptions {
         noCompress "tflite"
         noCompress "lite"
     }
 
For those interested in using your package.
Thank you for your information, time and package development.

Best
